### ISSUE TITLE
Consider making gutter and background the same color

### ISSUE THREAD

**Issue by sandover** [atom/solarized-dark-syntax#10]
Another subjective suggestion.  Having the gutter a different color is distracting.

diff --git a/stylesheets/syntax-variables.less b/stylesheets/syntax-variables.less
index eb07f24..2e7848f 100644
--- a/stylesheets/syntax-variables.less
+++ b/stylesheets/syntax-variables.less
@@ -21,8 +21,8 @@
 // Gutter colors
 @syntax-gutter-text-color: @base0;
 @syntax-gutter-text-color-selected: @syntax-gutter-text-color;
-@syntax-gutter-background-color: @base02;
-@syntax-gutter-background-color-selected: @base01;
+@syntax-gutter-background-color: @base03;
+@syntax-gutter-background-color-selected: @base02;

 // For git diff info. i.e. in the gutter
 @syntax-color-renamed: @blue;

**Comment by alistairholt** [comment]
I don't know if things have changed since 2014 but I had to use:

```
@import "syntax-variables";

atom-text-editor::shadow .gutter {
  background-color: @syntax-background-color;
}
````
