### ISSUE TITLE
Tree-Sitter JavaScript is not colored enough

### ISSUE THREAD

**Issue by jsg2021** [atom/solarized-dark-syntax#100]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

JS (and JSX) seem less colorful under tree-sitter (comparing to when using `language-babel` before)

### Steps to Reproduce

1. Turn on Tree-Sitter
2. Make sure to open a JS file with import/export/class/JSX syntax etc... and the language is JavaScript not Babel.
3. Observe the blandness :)

**Expected behavior:** To look at least as varied in color as without Tree-Sitter on (it falls back to Babel Language)

**Actual behavior:** Color is mostly default text color.

**Reproduces how often:** always

### Versions

```
Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.0
python 2.7.15
git 2.17.1
```

### Additional Information
This is with the JavaScript Language & Tree-Sitter on:
![tree-sitter](https://user-images.githubusercontent.com/577453/46153660-356c1400-c239-11e8-91ef-27a6720e3df4.png)

This is Babel Language (ignoring Tree-Sitter):
![babel](https://user-images.githubusercontent.com/577453/46153661-356c1400-c239-11e8-9464-2c98be3b2256.png)

**Comment by jsg2021** [comment]
Here is one dark for comparison... it would be nice if Solarized could be this varied.

![screen shot 2018-09-27 at 9 42 39 am](https://user-images.githubusercontent.com/577453/46153933-b2978900-c239-11e8-810e-1f48a33cdafb.png)

**Comment by darph** [comment]
This does not seem to be limited to JavaScript. Ruby looks similarly bland:

![screen shot 2018-11-01 at 17 31 01](https://user-images.githubusercontent.com/537743/47865423-76d57d80-ddfc-11e8-8df9-8828881b95a9.png)

**Comment by ryanolsonx** [comment]
I think I'll have time to dig into this. :)

**Comment by ryanolsonx** [comment]
PRs added for solarized dark (https://github.com/atom/solarized-dark-syntax/pull/104) and light (https://github.com/atom/solarized-light-syntax/pull/47).

It should be much improved. Other improvements will come from improvements to the language-javascript package that will merge shortly. As for the ruby highlighting, it looks like there's some issues with the language-ruby package. I think there's some issues already created that will be resolved soon.
