### ISSUE TITLE
Bracket matching indicator is almost no visible

### ISSUE THREAD

**Issue by chris-asl** [atom/solarized-dark-syntax#33]
Hello, 

I am using Atom (0.165.0) on my Ubuntu 14.04 system (64-bit) with the solarized-dark theme and the bracket matching indicator is almost no visible at all.  
I've added this

```
.bracket-matcher .region {
  border-bottom: 5px solid white;
  position: absolute;
}
```
to my style sheet to make it more visible, but failed.

It seems as if there is another layer above the indicator, that's making the indicator obscure.

This is how it looks:
![brackets](https://cloud.githubusercontent.com/assets/2846837/5579164/cba33d94-903e-11e4-9e2c-a75d7bacc4f1.png)

and this is how it looks in the *Atom Dark* theme:  
![brackets-dark](https://cloud.githubusercontent.com/assets/2846837/5579201/56e15198-903f-11e4-9965-3b542d6f831e.png)

As you can see, it's much much clearer.

If there's somewhere I can look for fixing it and submitting a pr, just tell me so.

Regards,
Chris

**Comment by chris-asl** [comment]
Happy New Year to all! 

@clhynfield Thank you for providing the link to the commit. It helped me resolve my issue!
Only problem I had, was not finding how to update the solarized-dark-syntax package. 
I've tried cloning it into the `~/.atom/packages` directory, but it didn't show up as a new syntax theme.

**Comment by kevinsawicki** [comment]
> Only problem I had, was not finding how to update the solarized-dark-syntax package. 

It is bundled with Atom so if you are on version 0.166 (the latest version) of Atom then then latest version of this theme, 0.30.0, will be included with it.
