### ISSUE TITLE
No longer highlighting syntax properly

### ISSUE THREAD

**Issue by davidpaulhunt** [atom/solarized-dark-syntax#40]
![screen shot 2015-05-18 at 11 54 39 am](https://cloud.githubusercontent.com/assets/6889054/7684519/b45a8c72-fd54-11e4-96af-03f5b25c59ce.png)

**Comment by lee-dohm** [comment]
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* What is not happening that you expect to happen?

**Comment by lee-dohm** [comment]
Closing as duplicate of #41. Please subscribe there for updates.
