### ISSUE TITLE
JavaScript syntax is not correct

### ISSUE THREAD

**Issue by themistersuit** [atom/solarized-dark-syntax#41]
Looks like an update to atom has resulted in the syntax for javascript -- specifically key words -- not looking correct.

**Comment by themistersuit** [comment]
![screen shot 2015-05-19 at 10 13 20 am](https://cloud.githubusercontent.com/assets/1526827/7706381/bed4f780-fe0f-11e4-88fa-b61e28f413af.png)

**Comment by schmittyjd** [comment]
Actually the syntax was overhauled in PR #35 This more accurately matches the syntax highlighting given by editors like textmate and sublime
