### ISSUE TITLE
Update solarized dark on atom 1.0

### ISSUE THREAD

**Issue by schmittyjd** [atom/solarized-dark-syntax#45]
Congrats to all those of the core atom team on 1.0! 
I have a question. If any of you core team members could eleborate on how changes to this repo (a syntax theme provided by default with atom) gets updated? There have been 2 pretty cool changes I have made and pulled in (enhanced js and jsx highlighting) that have still yet to appear on atom (even as of 1.0) would anyone care to elaborate?

**Comment by benogle** [comment]
We need to publish a new version and place the new version num into the atom/atom package json. I can do that tomorrow.

**Comment by benogle** [comment]
Both solarized themes are in atom master now, and will be out in the next version of atom

**Comment by schmittyjd** [comment]
woohoo!

**Comment by benogle** [comment]
Looks like the tags were a little messed up. Next time, can you run `apm publish minor` where `minor` can be `major`, `minor`, or `patch`. That will update the package json, make the tag, push the tag, and register the new version with apm. Should be good to go now for the current versions.
