### ISSUE TITLE
Incorrect syntax highlighting with Go

### ISSUE THREAD

**Issue by johngb** [atom/solarized-dark-syntax#47]
The syntax highlighting for Go seems to be incorrect when compared to the reference implementations in Vim, Emacs, and Sublime text.  For reference, here is the same code:

Atom
![screenshot 2015-08-04 18 28 29](https://cloud.githubusercontent.com/assets/44588/9066356/5c9ad184-3ad7-11e5-9e6b-1e88daf896cd.png)

Sublime Text 3
![screenshot 2015-08-04 18 28 49](https://cloud.githubusercontent.com/assets/44588/9066365/640c5b54-3ad7-11e5-8197-51fa5514a886.png)

I am using Atom 1.0.3 on OSX 10.9.5.

**Comment by franklinexpress** [comment]
very annoying, i know
