### ISSUE TITLE
Java syntax highlighting

### ISSUE THREAD

**Issue by ibocon** [atom/solarized-dark-syntax#51]
In dark solarized theme & ubuntu 14.04,
Most color used in under source code is just blue!
Better colored source codes make users better to get into code.

``` java
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class Application implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(Application.class);

    public static void main(String args[]) {
        SpringApplication.run(Application.class);
    }

    @Override
    public void run(String... strings) throws Exception {
        RestTemplate restTemplate = new RestTemplate();
        Quote quote = restTemplate.getForObject("http://gturnquist-quoters.cfapps.io/api/random", Quote.class);
        log.info(quote.toString());
    }
}

```
To be specific,

in function signature,
```
scope returnType functionName (arguments)
````
are just blue color.

even import are all colored blue..
```
import pakagePath.function
```
make pakagePath and Function should be colored differently for user interface.

Even, className is colored blue.

Therefore, I suggest to change coloring policy for Java source code.

**Comment by schmittyjd** [comment]
could you provide a screenshot to help explain? I don't quite understand your concern

**Comment by ibocon** [comment]
![report](https://cloud.githubusercontent.com/assets/9730869/10902394/d520bbb4-81c2-11e5-9e62-f788c953beeb.png)

Sorry for late report.

So, as you can see on the picture,
 'function' name is not distinguishable well.
'Exception' is also blue.

**Comment by schmittyjd** [comment]
ok I see. So this mainly has to do with the java highlighting. This can be changed by adding a <code>java.less</code> file describing highlighting specifics for java. (see any of the other language files in the repo as an example. I am very busy in other pursuits currently, I'm sure one of the other contributors would be able to help out

**Comment by schmittyjd** [comment]
also to find out what css classes are used to describe each part of the codes syntax, open atoms chrome console and inspect the elements. Hope this helps!

**Comment by ibocon** [comment]
![screenshot from 2015-11-11 23 55 39](https://cloud.githubusercontent.com/assets/9730869/11111555/d0f26cea-88cf-11e5-8bc5-1bfc5f304a7f.png)

I am currently working on creating 

>java.less

However, I am having organizing trouble because I can not understand the grammar's concept.
Should I look up 
>atom/language-java
project to understand how they organized?

**Comment by simurai** [comment]
Yes, `atom/language-java` defines all the tokens that can be styled by themes. It follows somwhat the [TextMate naming conventions](https://manual.macromates.com/en/language_grammars#naming_conventions).

Now, which color to use for which token.. hmm.. maybe stay close to the overrides of the other languages: https://github.com/atom/solarized-dark-syntax/tree/master/styles. But not sure how consistent they are.

Also, there is the question if this theme should match Sublime and the TextMate version, see #55. If so, then the styles in `base.less` would change and overriding for Java might  not even be needed. It would look like this: https://tmtheme-editor.herokuapp.com/#!/editor/theme/Solarized%20(dark)

![screen shot 2015-11-12 at 4 30 50 pm](https://cloud.githubusercontent.com/assets/378023/11112877/cf2e6c0c-895a-11e5-9344-e02e2a90df29.png)
