### ISSUE TITLE
Add cursor line

### ISSUE THREAD

**Issue by simurai** [atom/solarized-dark-syntax#60]
Currently the gutter highlights the current line:

![screen shot 2016-01-27 at 9 08 50 am](https://cloud.githubusercontent.com/assets/378023/12599495/bc250920-c4d5-11e5-95db-de93c0301fb9.png)

**Question**: Should instead the line in the editor be highlighted? That would match how the original theme is styled: http://ethanschoonover.com/solarized

![solarized-fontsamples-dark](https://cloud.githubusercontent.com/assets/378023/12599520/f68053fe-c4d5-11e5-9e36-e2ecde5105a6.png)

**Comment by MayhemYDG** [comment]
I think it should be a 1:1 port of the solarized theme, so :+1:
People transitioning from a different text editor to Atom while keeping Solarized as their theme should feel right at home.
The color of the line number should be darker as well.

**Comment by schmittyjd** [comment]
:+1: I'm for it
