### ISSUE TITLE
Latex broken in last update?

### ISSUE THREAD

**Issue by FlorianRohm** [atom/solarized-dark-syntax#64]
Hi there,
I just updated Atom from 1.5.4 to 1.6.1 and also got the new solarized 1.0.1.

I have to admit, there were quite some breaking changes.
Current view:
![screenshot from 2016-03-30 13 44 48](https://cloud.githubusercontent.com/assets/6051501/14141160/b2bd3dba-f67d-11e5-805c-cb6704801e39.png)

Keywords: blue, were red
\: red, was yellow
And most important: stuff in equations is not highlighted anymore (I don't think it was a change in language-latex, as other packages do highlight it)

Reference from solarized homepage:
![Reference](http://ethanschoonover.com/solarized/img/screen-tex-dark.png)

I think the old design was much more fitting, yet not like the proposed one.
Was this change intentional, or is there hope it will get fixed?

Greetings

**Comment by simurai** [comment]
Closing as `stale`.
