### ISSUE TITLE
Syntax highlighting in SCSS

### ISSUE THREAD

**Issue by bdielman** [atom/solarized-dark-syntax#68]
Noticed that when you nest selectors, the closing curly brace will lose its highlighting.

![scss-example](https://cloud.githubusercontent.com/assets/94547/17089755/bc9837f6-51f7-11e6-8440-d8f51fc75396.png)

**Comment by 50Wliu** [comment]
I am relatively sure that this will be fixed starting in Atom 1.10.0.

In the future these issues should be reported on the `atom/language-sass` repository.
