### ISSUE TITLE
HTML Comments w/URL Incorrectly Colored

### ISSUE THREAD

**Issue by grayghostvisuals** [atom/solarized-dark-syntax#73]
I started a sep. issue with JS having the same problems, but it also happens with HTML comments. Anything in a comment should be grayed out like the screenshot attached.

![screenshot 2016-09-27 09 31 24](https://cloud.githubusercontent.com/assets/934322/18875823/5e6b67c2-8495-11e6-9954-d8c4aded0343.png)

**Comment by simurai** [comment]
@grayghostvisuals Thanks..

This should also be fixed with https://github.com/atom/solarized-dark-syntax/pull/72. Gonna be in Atom `1.12`.
