### ISSUE TITLE
Highlighting of string and docstring

### ISSUE THREAD

**Issue by dpo** [atom/solarized-dark-syntax#74]
I'm told `string` and `docstring` are treated differently in this theme, which causes highlighting issues. I'm specifically editing files in the Julia language and I posted screenshots [here](https://github.com/JunoLab/atom-julia-client/issues/190#issuecomment-250323327).

Thanks.

**Comment by simurai** [comment]
Should be fixed in Atom `1.12`.

**Comment by dpo** [comment]
Thanks!
