### ISSUE TITLE
URLs improperly highlighted for CSS-esque comment within scss file

### ISSUE THREAD

**Issue by grayghostvisuals** [atom/solarized-dark-syntax#78]
![screenshot 2016-11-06 18 10 04](https://cloud.githubusercontent.com/assets/934322/20042668/5f22a71c-a44c-11e6-8c93-1994cff51da5.png)

The above is used for a WordPress stylesheet using `.scss` syntax.

**Comment by simurai** [comment]
This should already be fixed:

![image](https://user-images.githubusercontent.com/378023/44571503-e0f9f280-a7bb-11e8-9bef-b4d7232eaeef.png)
