### ISSUE TITLE
Code Sample in PHP Comment Improperly highlighted and colored

### ISSUE THREAD

**Issue by grayghostvisuals** [atom/solarized-dark-syntax#79]
![screenshot 2016-11-06 18 13 34](https://cloud.githubusercontent.com/assets/934322/20042702/c8f9639c-a44c-11e6-849a-09a9b995b15d.png)

Typically the PHP code sample in the PHP comment would be grayed out.

**Comment by simurai** [comment]
The code sample seems to be `invalid`?

```php
<?php
/**
 *
<?php class getAdder { } ?>
 *
 */
?>
```

It should be greyed out once you add an '*' in front

```php
<?php
/**
 *
 * <?php class getAdder { } ?>
 *
 */
?>
```
