### ISSUE TITLE
Add support of language-markdown

### ISSUE THREAD

**Issue by ungooglable** [atom/solarized-dark-syntax#87]
[https://atom.io/packages/language-markdown](https://atom.io/packages/language-markdown)

### See also

- an [item in their FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md#some-of-my-markdown-elements-arent-highlighted)
- a [comment on grammar classes issue](https://github.com/burodepeper/language-markdown/issues/167)

**Comment by ooJerryLeeoo** [comment]
@ungooglable Like this ??

![Markdown](https://raw.githubusercontent.com/ooJerryLeeoo/atom-solarized-dark-syntax/master/screenshot/Markdown.png)

**Comment by ryanolsonx** [comment]
I’m willing to add markdown support 👌

**Comment by andrademfg** [comment]
Markdown support would be brilliant, thanks!

**Comment by ryanolsonx** [comment]
I'm sorry. I thought this was requesting better support for the built-in language-markdown grammar. I may add support for this in the future, but right now, I don't have the time to work on adding this support. So this issue is up for grabs right now.
